### ISSUE TITLE
solver

### ISSUE THREAD

**Issue by QXZhong1998** [snilsn/SLM_OpenFOAM#2]
I am new to OpenFOAM, and I am also planning to use openfoam to simulate the melting process of SLM, could you provide your solver for reference. Thanks!

**Comment by snilsn** [comment]
Hey,

to be honest I never finished this project, but I hope I can give you at least some hints where to start:

In principle, beamWeldFoam (https://github.com/tomflint22/beamWeldFoam) should contain everything you need plus this solver is already verified on some cases. The _fvSolution_-file in the system directory of the tutorials contains the properties of the laser. Just takes a while to figure out how it works and to adapt to your situation.

Another Idea would be to use the _icoreactingmultiphaseinterfoam_-solver and this paper: https://iopscience.iop.org/article/10.1088/1361-651X/ac4a26

Good luck!

**Comment by QXZhong1998** [comment]
Thank you very much for your help and advice, it helps me a lot



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/23/2022 15:40 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [snilsn/SLM_OpenFOAM] solver (Issue #2) |

Hey,

to be honest I never finished this project, but I hope I can give you at least some hints where to start:

In principle, beamWeldFoam (https://github.com/tomflint22/beamWeldFoam) should contain everything you need plus this solver is already verified on some cases. The fvSolution-file in the system directory of the tutorials contains the properties of the laser. Just takes a while to figure out how it works and to adapt to your situation.

Another Idea would be to use the icoreactingmultiphaseinterfoam-solver and this paper: https://iopscience.iop.org/article/10.1088/1361-651X/ac4a26

Good luck!
